/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gcp.VUE;

import gcp.CONTROLLER.RepositoryPosteBoitePostale;
import gcp.MODELES.BoitePostale;
import gcp.MODELES.Poste;
import gcp.MODELES.PosteBoiteDetails;
import java.text.MessageFormat;
import java.util.List;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EXPENDATEUR
 */
public class ListePoste extends javax.swing.JPanel {
RepositoryPosteBoitePostale repository;
    public ListePoste() {
        initComponents();
        repository=new RepositoryPosteBoitePostale();
        loadPosteBoiteData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        poste = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(122, 112, 140));
        jPanel1.setPreferredSize(new java.awt.Dimension(1192, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LES POSTES ET LEURS BOITES POSTAUX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel1)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        poste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOM POSTE", "REGIME", "PAYS", "VILLE", "NUMERO BP", "TYPE BOITE POSTAL", "ETAT POSTAL"
            }
        ));
        jScrollPane1.setViewportView(poste);

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1036, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
public void loadPosteBoiteData() {
    // Récupérer les détails des postes et boîtes postales
    List<PosteBoiteDetails> posteBoiteDetails = repository.readPosteBoiteDetails();

    // Configurer le modèle de table
    DefaultTableModel tableModel = (DefaultTableModel) poste.getModel(); // Assurez-vous que 'poste' est votre JTable
    tableModel.setRowCount(0); // Vider le tableau avant d'ajouter de nouvelles données

    // Remplir le tableau avec les données récupérées
    for (PosteBoiteDetails details : posteBoiteDetails) {
        Poste poste = details.getPoste();
        BoitePostale boitePostale = details.getBoitePostale();

        Object[] rowData = {
            poste.getNomPoste(),
            poste.getRegime(),
            poste.getPays(),
            poste.getVille(),
            boitePostale.getNumBP(),
            boitePostale.getTypeBP(),
            boitePostale.getEtatBP()
        };
        tableModel.addRow(rowData); // Ajouter la ligne au modèle de la table
    }
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        printTable();
    }//GEN-LAST:event_jButton1ActionPerformed
private void printTable() {
    MessageFormat title= new MessageFormat("RAPPORT DES POSTAUX");
    MessageFormat pieds= new MessageFormat("PAGE {0,number,Integer}");
    
    try {
       PrintRequestAttributeSet set =new HashPrintRequestAttributeSet();
       set.add(OrientationRequested.LANDSCAPE);
       poste.print(JTable.PrintMode.FIT_WIDTH,title,pieds,true,set,true);
       JOptionPane.showMessageDialog(this, "L'impression reussie.");
    } catch (java.awt.print.PrinterException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Erreur lors de l'impression.");
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable poste;
    // End of variables declaration//GEN-END:variables
}
